using System.Collections.Generic;

namespace BO.Facturacion
{
    /*
    //https://api.contazara.es/api/2019-06-01/meters/readings/search?readType=offline&dateType=read_date&fromDate=20231015&toDate=20231016&action=get&plrType=1&page=0&perPage=30
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    */

    public class Metadata
    {
        public int page { get; set; }
        public int perPage { get; set; }
        public int pageCount { get; set; }
        public int totalCount { get; set; }
        public int totalPages { get; set; }
        public string self { get; set; }
        public string next { get; set; }
        public object previous { get; set; }
        public string first { get; set; }
        public string last { get; set; }
    }

    public class Record
    {
        public int? alarmStat { get; set; }
        public object alarm { get; set; }
        public int? alrModeH { get; set; }
        public int? alrPerMultH { get; set; }
        public object alrPerMultL { get; set; }
        public int? alrPerUnitH { get; set; }
        public object alrPerUnitL { get; set; }
        public int battery { get; set; }
        public int batteryDetail { get; set; }
        public int? bus { get; set; }
        public string date { get; set; }
        public object decimalPoint { get; set; }
        public object eraseDateWd { get; set; }
        public object eraseTimeWd { get; set; }
        public string errorFlags { get; set; }
        public int? firstDofW1 { get; set; }
        public int? firstDofW2 { get; set; }
        public int? firstDofW3 { get; set; }
        public int? firstDofW4 { get; set; }
        public int? firstDofW5 { get; set; }
        public int? firstDofW6 { get; set; }
        public int? firstHour1 { get; set; }
        public int? firstHour2 { get; set; }
        public int? firstHour3 { get; set; }
        public int? firstHour4 { get; set; }
        public int? firstHour5 { get; set; }
        public int? firstHour6 { get; set; }
        public string flowRateUnit { get; set; }
        public float? histogram1QminCfg { get; set; }
        public object histogram1Time { get; set; }
        public float? histogram1Vol { get; set; }
        public float? histogram10QminCfg { get; set; }
        public object histogram10Time { get; set; }
        public float? histogram10Vol { get; set; }
        public float? histogram11QminCfg { get; set; }
        public object histogram11Time { get; set; }
        public float? histogram11Vol { get; set; }
        public float? histogram12QminCfg { get; set; }
        public object histogram12Time { get; set; }
        public float? histogram12Vol { get; set; }
        public float? histogram2QminCfg { get; set; }
        public object histogram2Time { get; set; }
        public float? histogram2Vol { get; set; }
        public float? histogram3QminCfg { get; set; }
        public object histogram3Time { get; set; }
        public float? histogram3Vol { get; set; }
        public float? histogram4QminCfg { get; set; }
        public object histogram4Time { get; set; }
        public float? histogram4Vol { get; set; }
        public float? histogram5QminCfg { get; set; }
        public object histogram5Time { get; set; }
        public float? histogram5Vol { get; set; }
        public float? histogram6QminCfg { get; set; }
        public object histogram6Time { get; set; }
        public float? histogram6Vol { get; set; }
        public float? histogram7QminCfg { get; set; }
        public object histogram7Time { get; set; }
        public float? histogram7Vol { get; set; }
        public float? histogram8QminCfg { get; set; }
        public object histogram8Time { get; set; }
        public float? histogram8Vol { get; set; }
        public float? histogram9QminCfg { get; set; }
        public object histogram9Time { get; set; }
        public float? histogram9Vol { get; set; }
        public string hold1Date { get; set; }
        public float? hold1Index { get; set; }
        public string hold1Time { get; set; }
        public string hold2Date { get; set; }
        public float? hold2Index { get; set; }
        public string hold2Time { get; set; }
        public object horAlarmN { get; set; }
        public int id { get; set; }
        public int inputFormat { get; set; }
        public int idCustomer { get; set; }
        public object idSubscriber { get; set; }
        public object idFile { get; set; }
        public int idReadsFile { get; set; }
        public object inBus { get; set; }
        public float? indAlarmH { get; set; }
        public object indAlar { get; set; }
        public float? indexLastHour { get; set; }
        public float indexVol { get; set; }
        public int? lastDofW1 { get; set; }
        public int? lastDofW2 { get; set; }
        public int? lastDofW3 { get; set; }
        public int? lastDofW4 { get; set; }
        public int? lastDofW5 { get; set; }
        public int? lastDofW6 { get; set; }
        public int? lastHour1 { get; set; }
        public int? lastHour2 { get; set; }
        public int? lastHour3 { get; set; }
        public int? lastHour4 { get; set; }
        public int? lastHour5 { get; set; }
        public int? lastHour6 { get; set; }
        public string lastReadDate { get; set; }
        public float? lastReadIndex { get; set; }
        public string lastReadTime { get; set; }
        public string lastStartDate { get; set; }
        public string lastStartTime { get; set; }
        public object lastStopDate { get; set; }
        public object lastStopTime { get; set; }
        public int? leakTime { get; set; }
        public string manufacturer { get; set; }
        public object multiplierUnit { get; set; }
        public int? normalTime { get; set; }
        public string program { get; set; }
        public string qmax { get; set; }
        public int? qmaxDofW { get; set; }
        public string qmaxDate { get; set; }
        public string qmaxTime { get; set; }
        public int? qmaxR { get; set; }
        public int? qminDofW { get; set; }
        public string qminDate { get; set; }
        public string qminTime { get; set; }
        public int? qminR { get; set; }
        public string readDate { get; set; }
        public string readDateTime { get; set; }
        public string readDateTimeUtc { get; set; }
        public string readTime { get; set; }
        public int readType { get; set; }
        public object readingId { get; set; }
        public int? regUnit { get; set; }
        public float? regVol1 { get; set; }
        public float? regVol10 { get; set; }
        public float? regVol11 { get; set; }
        public float? regVol12 { get; set; }
        public float? regVol2 { get; set; }
        public float? regVol3 { get; set; }
        public float? regVol4 { get; set; }
        public float? regVol5 { get; set; }
        public float? regVol6 { get; set; }
        public float? regVol7 { get; set; }
        public float? regVol8 { get; set; }
        public float? regVol9 { get; set; }
        public object reportBusRead { get; set; }
        public object reportBusReadBasicRead { get; set; }
        public object reportBusReadExtendedRead { get; set; }
        public object reportBusReadExtendedARead { get; set; }
        public object reportBusReadVersionRead { get; set; }
        public object reportEnvironment { get; set; }
        public string reportIdInterface { get; set; }
        public string reportProgVersion { get; set; }
        public string reserved { get; set; }
        public int? reverseTime { get; set; }
        public float? reverseVolume { get; set; }
        public int? rtcCh { get; set; }
        public string rtcDate { get; set; }
        public int? rtcDofW { get; set; }
        public string rtcTime { get; set; }
        public string serialNumber { get; set; }
        public int? sleepTime { get; set; }
        public int? starts { get; set; }
        public string status { get; set; }
        public object supplyPoint { get; set; }
        public string type { get; set; }
        public string units { get; set; }
        public string version { get; set; }
        public float? volAlarmH { get; set; }
        public object volAlarmL { get; set; }
        public object volAlarmN { get; set; }
        public string volumeUnit { get; set; }
        public float? vrxx0 { get; set; }
        public float? vrxx1 { get; set; }
        public float? vrxx2 { get; set; }
        public float? vrxx3 { get; set; }
        public string wd1EndDaysOfWeek { get; set; }
        public string wd1EndTime { get; set; }
        public string wd1StartDaysOfWeek { get; set; }
        public string wd1StartMonths { get; set; }
        public string wd1StartTime { get; set; }
        public float? wd1Vol { get; set; }
        public string wd2EndDaysOfWeek { get; set; }
        public string wd2EndTime { get; set; }
        public string wd2StartDaysOfWeek { get; set; }
        public string wd2StartMonths { get; set; }
        public string wd2StartTime { get; set; }
        public float? wd2Vol { get; set; }
        public string wd3EndDaysOfWeek { get; set; }
        public string wd3EndTime { get; set; }
        public string wd3StartDaysOfWeek { get; set; }
        public string wd3StartMonths { get; set; }
        public string wd3StartTime { get; set; }
        public float? wd3Vol { get; set; }
        public string wd4EndDaysOfWeek { get; set; }
        public string wd4EndTime { get; set; }
        public string wd4StartDaysOfWeek { get; set; }
        public string wd4StartMonths { get; set; }
        public string wd4StartTime { get; set; }
        public float? wd4Vol { get; set; }
        public string wd5EndDaysOfWeek { get; set; }
        public string wd5EndTime { get; set; }
        public string wd5StartDaysOfWeek { get; set; }
        public string wd5StartMonths { get; set; }
        public string wd5StartTime { get; set; }
        public float? wd5Vol { get; set; }
        public string wd6EndDaysOfWeek { get; set; }
        public string wd6EndTime { get; set; }
        public string wd6StartDaysOfWeek { get; set; }
        public string wd6StartMonths { get; set; }
        public string wd6StartTime { get; set; }
        public float? wd6Vol { get; set; }
        public string wd7EndDaysOfWeek { get; set; }
        public string wd7EndTime { get; set; }
        public string wd7StartDaysOfWeek { get; set; }
        public string wd7StartMonths { get; set; }
        public string wd7StartTime { get; set; }
        public float? wd7Vol { get; set; }
        public object erasableDate { get; set; }
        public object aplusFrame { get; set; }
    }

    public class Root
    {
        public Metadata metadata { get; set; }
        public List<Record> records { get; set; }
    }
}
