SELECT * 
--UPDATE O SET otivDescParaCartas='BUEN ESTADO DE CONSERVACIÓN DE LA INSTALACIÓN HIDRÁULICA'
FROM otInspeccionesValidaciones AS O
WHERE otivDescParaCartas = 'ESTADO DE CONSERVACIÓN DE LA INSTALACIÓN HIDRÁULICA (BUENO, MALO)'